// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6r0cql8pftO5FNudVa2VRc-V0rbAuLTo',
    appId: '1:399577887972:web:c09cc453eb65b923ed28f1',
    messagingSenderId: '399577887972',
    projectId: 'my-news-app-c3e88',
    authDomain: 'my-news-app-c3e88.firebaseapp.com',
    storageBucket: 'my-news-app-c3e88.appspot.com',
    measurementId: 'G-2T2ZR8J9W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4FOYe8LzAtXrKbsNMFrkXlXuvCtxgRW4',
    appId: '1:399577887972:android:752a32dd75907936ed28f1',
    messagingSenderId: '399577887972',
    projectId: 'my-news-app-c3e88',
    storageBucket: 'my-news-app-c3e88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABkUFajMVYRGptuSqhldReSn6e0ttrfc8',
    appId: '1:399577887972:ios:d234cbd47f3aef83ed28f1',
    messagingSenderId: '399577887972',
    projectId: 'my-news-app-c3e88',
    storageBucket: 'my-news-app-c3e88.appspot.com',
    iosBundleId: 'com.example.myNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABkUFajMVYRGptuSqhldReSn6e0ttrfc8',
    appId: '1:399577887972:ios:d234cbd47f3aef83ed28f1',
    messagingSenderId: '399577887972',
    projectId: 'my-news-app-c3e88',
    storageBucket: 'my-news-app-c3e88.appspot.com',
    iosBundleId: 'com.example.myNewsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6r0cql8pftO5FNudVa2VRc-V0rbAuLTo',
    appId: '1:399577887972:web:a8532439e783407ded28f1',
    messagingSenderId: '399577887972',
    projectId: 'my-news-app-c3e88',
    authDomain: 'my-news-app-c3e88.firebaseapp.com',
    storageBucket: 'my-news-app-c3e88.appspot.com',
    measurementId: 'G-1H27PD9WYB',
  );
}
